# Generated by Django 4.1.2 on 2022-12-05 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline", models.CharField(max_length=128, verbose_name="Avis")),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            ("0", "Zero Etoile"),
                            ("1", "Une Etoile"),
                            ("2", "Deux Etoiles"),
                            ("3", "Trois Etoiles"),
                            ("4", "Quatre Etoiles"),
                            ("5", "Cinq Etoiles"),
                        ],
                        default="5",
                        max_length=5,
                        verbose_name="Note",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        default="", max_length=8192, verbose_name="Commentaire"
                    ),
                ),
                ("time_created", models.DateTimeField(auto_now_add=True)),
                (
                    "ticket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tickets.ticket",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
