# Generated by Django 4.1.2 on 2022-11-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0005_alter_review_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.CharField(
                choices=[
                    ("0", "Zéro Étoile"),
                    ("1", "Une Étoile"),
                    ("2", "Deux Étoiles"),
                    ("3", "Trois Étoiles"),
                    ("4", "Quatre Étoiles"),
                    ("5", "Cinq Étoiles"),
                ],
                default="5",
                max_length=5,
                verbose_name="Note",
            ),
        ),
    ]
